### ISSUE TITLE
24620226_OperacionesBásicas

### ISSUE THREAD

**Issue by KarenIMont** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-KarenIMont#1]
[OperacionesBasicas_KarenIraisMontalvoReyes.pdf](https://github.com/user-attachments/files/16832392/OperacionesBasicas_KarenIraisMontalvoReyes.pdf)

**Comment by Ivan-PerezZ** [comment]
Portada:22/25
Procedimiento:24/25
Figuras ilustraciones y fotografias :25/25
Resultados y conclusiones:24/25
Calificacion final:19

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
